---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by imyzt.
--- DateTime: 2020/1/30 12:46 下午
---数组的操作, 就是用table实现的, key为数组下标
---

local arr = {}

for i = 1, 10 do
    --始终插入(第二个参数)第一个位置, 所以相当于倒序插入
    --table.insert(arr, 1, i)
    --第二种插入方式
    arr[i] = i;
end

--遍历一
for key, var in pairs(arr) do
    --key就是索引
    print(key, var)
end

print('-------')

--遍历二
for i = 1, #arr do
    print(arr[i])
end

--获取数组长度
print("数组长度=", #arr)