---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by imyzt.
--- DateTime: 2020/1/30 11:50 上午
---

--全局变量
globalVariable = 200

function fly(param)
    --局部变量
    local localVariable = 100
    --局部变量	100
    print('局部变量', localVariable)
    --方法入参: 	200
    print("方法入参: ", param)
end

--此处无法访问, 输出为 nil
print('局部变量', localVariable)


fly(globalVariable)
print('全局变量', globalVariable)

--输出为
--局部变量	nil
--局部变量	100
--方法入参: 	200
--全局变量	200