---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by imyzt.
--- DateTime: 2020/1/30 12:11 下午
---方法定义, 分支, 循环
---

function max(arr)

    local max = arr[1]
    --通过 # 获取数组长度, 括号内先对arr进行 nil判断,不为nil则获取长度
    local len = (arr and #arr) or 0;

    for i = 1, len do

        local curr = arr[i]
        if curr > max then
            max = curr
        elseif curr == max then
        --    不变, max还是自己
        else
        --    不变, max还是自己
        end
    end
    return max
end

local list = {1,2,3,299}
local maxNum = max(list)
print("最大值为:", maxNum)

for i = 1, 100 do
    print('i=', i)
end