---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by imyzt.
--- DateTime: 2020/1/30 12:31 下午
---表的基本使用
---

--表的三种定义方式
mysqlConfig = {
    host="localhost",
    username="root"
}
--表的新增
mysqlConfig.password = "123"
mysqlConfig["driver"] = "com.mysql.jdbc.Driver"

--表的两种查询方式
print('原始的pwd', mysqlConfig.password)
print('原始的url', mysqlConfig["url"])

--表的修改
mysqlConfig.password = "321"
print('修改后的pwd', mysqlConfig.password)

--表的删除
mysqlConfig.password = nil
print('删除后的pwd', mysqlConfig.password)


print('---------')

--表的遍历 pairs
for key, var in pairs(mysqlConfig) do
    print(key, var)
end
