server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:~/mydb
    driver-class-name: org.h2.Driver
    username: root
    password: test
  h2:
    console:
      path: /h2-console
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-case: true
